version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"

  # Maintain dependencies for npm
  - package-ecosystem: "docker"
    directory: "/"

  # Maintain dependencies for Composer
  - package-ecosystem: "dotnet"
    directory: "/"
