version: "3.8"

services:
    api:
        build: 
            context: ./src
            dockerfile: Dockerfile.api
        image: niccoudev/hateoas-api:1.0
        ports:
            - "5010:5010"
    
    front:
        build:
            context: ./src
            dockerfile: Dockerfile.front
        image: niccoudev/hateoas-front:1.0
        ports:
            - "8020:80"
