FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

WORKDIR /app

COPY ./WebApi.Repository/ ./WebApi.Repository/
COPY ./WebApi.Core/ ./WebApi.Core/
COPY ./WebApi/ ./WebApi/

RUN bash

RUN dotnet restore ./WebApi

RUN dotnet publish -c Release -o out ./WebApi/

FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app

COPY --from=build-env /app/out .

EXPOSE 5010

ENTRYPOINT ["dotnet", "WebApi.dll"]